apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  name: rhdh
  namespace: setup-rhdh
spec:
  application:
    appConfig:
      mountPath: /opt/app-root/src
      # This instructs the operator to mount the ConfigMap
      # that you created into the Backstage Pods
      configMaps:
        - name: rhdh-config
    route:
      enabled: true
  database:
    enableLocalDb: true
