apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: setup-rhdh
stringData:
  KEYCLOAK_BASE_URL: https://sso.apps.cluster-fpfw7.dynamic.redhatworkshops.io
  KEYCLOAK_LOGIN_REALM: trusted-artifact-signer
  KEYCLOAK_REALM: trusted-artifact-signer
  KEYCLOAK_CLIENT_ID: rhdh
  KEYCLOAK_CLIENT_SECRET: your-password-here
