apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-plugins-root
  namespace: setup-rhdh
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
